export const PROJECT_INFO = [
  {
    id: "101",
    picture: "/assets/image/blogApp.png",
    name: "Blog App",
    category: "MERN",
    githubFE: "https://github.com/Shivam-yadav0206/Blog-App-FrontEnd",
    githubBE: "https://github.com/Shivam-yadav0206/Blog-App-BackEnd",
    url: "https://blog-app-fe-delta.vercel.app/login",
  },
  {
    id: "102",
    picture: "/assets/image/socioMedia.png",
    name: "SocioMedia",
    category: "MERN",
    githubFE: "https://github.com/Shivam-yadav0206/SocioMedia-Frontend",
    githubBE: "https://github.com/Shivam-yadav0206/SocioMedia-Backend",
    url: "https://rad-churros-620ad0.netlify.app/",
  },
  {
    id: "103",
    picture: "/assets/image/",
    name: "Zwiggy",
    category: "Js",
    githubFE: "",
    githubBE: "",
    url: "",
  },
  {
    id: "104",
    picture: "/assets/image/moviesHub.png",
    name: "MoviesHub",
    category: "Js",
    githubFE: "https://github.com/Shivam-yadav0206/MoviesHub-FrontEnd",
    githubBE: "https://github.com/Shivam-yadav0206/MoviesHub-FrontEnd",
    url: "https://movies-hub-front-end.vercel.app/",
  },
  {
    id: "105",
    picture: "/assets/image/quizzy.png",
    named: "Quizzy",
    category: "MEVN",
    githubFE: "https://github.com/Shivam-yadav0206/Quizzy-Frontend",
    githubBE: "https://github.com/Shivam-yadav0206/Quizzy-Backend",
    url: "https://quizzyy.vercel.app/",
  },
  {
    id: "106",
    picture: "/assets/image/weatherApp.png",
    name: "Weather App",
    category: "Js",
    githubFE: "https://github.com/Shivam-yadav0206/Weather-App",
    githubBE: "https://github.com/Shivam-yadav0206/Weather-App",
    url: "https://shivam-yadav0206.github.io/Weather-App/",
  },
];
